# Generated by Django 2.0.6 on 2018-09-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_act', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('bill_history', models.TextField(default='', max_length=1000)),
                ('date', models.DateField(default='2018-09-25', max_length=100)),
                ('url', models.URLField(default='')),
                ('updated', models.BooleanField(default=False)),
                ('updated_at', models.DateField(default='2018-09-25', max_length=100)),
                ('associated_act', models.ManyToManyField(help_text='Select associated act', to='bill.AssociatedAct')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('con_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.URLField(default='')),
                ('url', models.URLField(default='')),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('url', models.URLField(default='')),
                ('created_date', models.DateField(default='2018-09-25', max_length=100)),
                ('approved_movement', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movement', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='bill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='Origin', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('panel_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Panel')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(default='Sponsor', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.TextField(max_length=255)),
                ('stage_info', models.TextField(default='Stage Info', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='deputy',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Party'),
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this bill', to='bill.Category'),
        ),
        migrations.AddField(
            model_name='bill',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Origin'),
        ),
        migrations.AddField(
            model_name='bill',
            name='senator',
            field=models.ManyToManyField(help_text='Select a td for this bill', to='bill.Senator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.ManyToManyField(help_text='Select a sponsor for this bill', to='bill.Sponsor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Stage'),
        ),
        migrations.AddField(
            model_name='bill',
            name='td',
            field=models.ManyToManyField(help_text='Select a td for this bill', to='bill.Deputy'),
        ),
    ]
