# Generated by Django 2.0.6 on 2018-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default='2018-09-26', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateField(default='2018-09-26', max_length=100),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_date',
            field=models.DateField(default='2018-09-26', max_length=100),
        ),
    ]
