# Generated by Django 2.0.6 on 2018-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20180926_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default='2018-09-27', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateField(default='2018-09-27', max_length=100),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_date',
            field=models.DateField(default='2018-09-27', max_length=100),
        ),
    ]
