# Generated by Django 2.0.6 on 2018-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20180927_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default='2018-09-28', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateField(default='2018-09-28', max_length=100),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_date',
            field=models.DateField(default='2018-09-28', max_length=100),
        ),
    ]
