# Generated by Django 2.0.6 on 2018-09-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritesmodel',
            name='favourited_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Bill'),
        ),
        migrations.AddField(
            model_name='citizenbill',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_bill', to='bill.Bill'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='favouritesmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Citizen'),
        ),
        migrations.AddField(
            model_name='citizenbill',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_bill', to='accounts.Citizen'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='bill.Bill'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='interests',
            field=models.ManyToManyField(related_name='interested_citizens', to='bill.Category'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='my_bills',
            field=models.ManyToManyField(through='accounts.CitizenBill', to='bill.Bill'),
        ),
    ]
