# Generated by Django 2.0.6 on 2018-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180925_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='email',
            field=models.EmailField(default='', max_length=300),
        ),
    ]
